### ISSUE TITLE
Infinite, no ground

### ISSUE THREAD

**Issue by GoalieSave25** [omarhuseynov011/NeoTrap#3]
Great Game!  I hadn't modded anything, I was just playing the game when the ground disappeared and I hadn't died, so I guess rnd generation stopped also, and it was just me and the starfield.  Image: http://i.imgur.com/KmsQOxF.png

**Comment by omarhuseynov011** [comment]
That's weird...
Perhaps what happened was that repositioning of the floor mesh failed, this can happen because of many reasons, and I certainly can't say why given no information log about what was happening at that moment. 
Thanks for the report though

**Comment by GoalieSave25** [comment]
No problem, being a three.js user, I have no idea how to use babylon.js, so I just didn't bother looking into the code, great game again though!  Also love your profile pic too, I have my own tabby cat as well :)
